version: '3.7'

services:
  wp:
    depends_on:
      - db
    build:
      context: ./
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - $WORDPRESS_EXTERNAL_PORT:80
    environment:
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
      WORDPRESS_DB_HOST: $WORDPRESS_DB_HOST
      WORDPRESS_CONFIG_EXTRA: |
        define( 'FS_METHOD', 'direct' );
    volumes:
      - ./:/var/www/html/wp-content
      - ./core:/var/www/html

  db:
    image: mariadb:latest
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/mysql

  adminer:
    env_file:
      - .env
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - $ADMINER_EXTERNAL_PORT:8080

  mailhog:
    image: mailhog/mailhog
    env_file:
      - .env
    ports:
      - $MAILHOG_SMTP_EXTERNAL_PORT:1025
      - $MAILHOG_EXTERNAL_PORT:8025
